### PR TITLE
fix(wassette): add exdev-safe fallback for component loading

### LINKED ISSUE #107: Invalid cross-device link
I'm trying to play with `wassette` in code. I enabled the `wassette` server but loading a component fails with `Invalid cross-device link`. 

```
2025-08-07 14:27:39.860 [info] Starting server Wassette
2025-08-07 14:27:39.861 [info] Connection state: Starting
2025-08-07 14:27:39.862 [info] Starting server from LocalProcess extension host
2025-08-07 14:27:39.870 [info] Connection state: Starting
2025-08-07 14:27:39.871 [info] Connection state: Running
2025-08-07 14:27:39.912 [warning] [server stderr] 2025-08-07T18:27:39.896434Z  INFO new{plugin_dir=/home/fmorency/.local/share/wassette/components}:new_with_clients:new_with_policy: wassette: Creating new LifecycleManager
2025-08-07 14:27:39.912 [warning] [server stderr] 2025-08-07T18:27:39.896708Z  INFO new{plugin_dir=/home/fmorency/.local/share/wassette/components}:new_with_clients:new_with_policy: wassette: LifecycleManager initialized successfully
2025-08-07 14:27:39.913 [warning] [server stderr] 2025-08-07T18:27:39.896724Z  INFO wassette: Starting MCP server with stdio transport
2025-08-07 14:27:39.924 [warning] [server stderr] 2025-08-07T18:27:39.916658Z  INFO rmcp::handler::server: client initialized
2025-08-07 14:27:39.925 [warning] [server stderr] 2025-08-07T18:27:39.916692Z  INFO serve_inner: rmcp::service: Service initialized as server peer_info=Some(InitializeRequestParam { protocol_version: ProtocolVersion("2025-06-18"), capabilities: ClientCapabilities { experimental: None, roots: Some(RootsCapabilities { list_changed: Some(true) }), sampling: Some({}) }, client_info: Implementation { name: "Visual Studio Code", version: "1.103.0" } })
2025-08-07 14:27:39.925 [warning] [server stderr] 2025-08-07T18:27:39.917307Z  INFO handle_tools_list:get_component_tools: mcp_server::components: Found components count=0
2025-08-07 14:27:39.925 [warning] [server stderr] 2025-08-07T18:27:39.917321Z  INFO handle_tools_list:get_component_tools: mcp_server::components: Total tools collected total_tools=0
2025-08-07 14:27:39.925 [info] Discovered 7 tools
2025-08-07 14:28:16.885 [warning] [server stderr] 2025-08-07T18:28:16.864833Z  INFO handle_tools_call{method_name=load-component}: mcp_server::tools: Handling tool call
2025-08-07 14:28:16.885 [warning] [server stderr] 2025-08-07T18:28:16.864871Z  INFO handle_tools_call{method_name=load-component}:handle_load_component{req=CallToolRequestParam { name: "load-component", arguments: Some({"path": String("oci://ghcr.io/yoshuawuyts/time:latest")}) } server_peer=PeerSink { tx: Sender { chan: Tx { inner: Chan { tx: Tx { block_tail: 0x561e12bdb6b0, tail_position: 0 }, semaphore: Semaphore { semaphore: Semaphore { permits: 1024 }, bound: 1024 }, rx_waker: AtomicWaker, tx_count: 3, rx_fields: "..." } } }, is_client: false }}: mcp_server::components: Loading component path="oci://ghcr.io/yoshuawuyts/time:latest"
2025-08-07 14:28:20.537 [warning] [server stderr] 2025-08-07T18:28:20.536568Z ERROR handle_tools_call{method_name=load-component}:handle_load_component{req=CallToolRequestParam { name: "load-component", arguments: Some({"path": String("oci://ghcr.io/yoshuawuyts/time:latest")}) } server_peer=PeerSink { tx: Sender { chan: Tx { inner: Chan { tx: Tx { block_tail: 0x561e12bdb6b0, tail_position: 0 }, semaphore: Semaphore { semaphore: Semaphore { permits: 1024 }, bound: 1024 }, rx_waker: AtomicWaker, tx_count: 3, rx_fields: "..." } } }, is_client: false }}: mcp_server::components: Failed to load component error=Failed to copy component to destination: /home/fmorency/.local/share/wassette/components. Error: Invalid cross-device link (os error 18) path="oci://ghcr.io/yoshuawuyts/time:latest"
2025-08-07 14:28:20.537 [warning] [server stderr] 2025-08-07T18:28:20.536599Z ERROR handle_tools_call{method_name=load-component}: mcp_server::tools: Tool call failed error=Failed to load component: oci://ghcr.io/yoshuawuyts/time:latest. Error: Failed to copy component to destination: /home/fmorency/.local/share/wassette/components. Error: Invalid cross-device link (os error 18)
```

Image

### PR DESCRIPTION
**Pull request by Mossaka**
implements fallback to copy+rename when rename returns error 18 indicating a EXDEV.

Closes #107 

Signed-off-by: Jiaxiao Zhou <duibao55328@gmail.com>

### CODE REVIEW

File: crates/wassette/src/lib.rs [hunk 1]
```diff
@@ -2187,4 +2251,40 @@ permissions:
 
         Ok(())
     }
+
+    #[test(tokio::test)]
+    async fn test_copy_to_rename_fast_path() -> Result<()> {
```
Comment (thomastaylor312) [inline crates/wassette/src/lib.rs]: Nit: maybe "happy_path" instead of "fast_path" I stared at this for like 30s before I figured out why it was called this

File: crates/wassette/src/lib.rs [hunk 2]
```diff
@@ -319,7 +319,43 @@ impl DownloadedResource {
                     file.file_name()
                         .context("Path to copy is missing filename")?,
                 );
-                tokio::fs::rename(file, dest).await?;
+                #[cfg(test)]
```
Comment (thomastaylor312) [inline crates/wassette/src/lib.rs]: I don't really love having test only code in the main code path, even if it is feature flagged. Given that this is a well documented error, I don't know that needing to add this block is worth adding the test as the logic is very clear and easily reviewable. Put another way, I don't think feature flagging this and needing to add all the code for `exdev_test_support` is worth testing whether it can handle a return value of `18`. If this were actually testing a cross device move, I'd be more open to it, but as it stands now, I don't think it is worth it.

Thoughts?

**Review by thomastaylor312 — COMMENTED** [review]
Fix is good to go, but I have concerns with adding test only code into the main code path here

File: crates/wassette/src/lib.rs (hunk 2 above)
Comment (Mossaka) [reply crates/wassette/src/lib.rs]: yeah fair, I had a hard time implementing a test case for cross-device so had to simulate it here. I can remove the tests if we are confident about the logic being implemented here.

File: crates/wassette/src/lib.rs [hunk 3]
```diff
@@ -319,7 +319,43 @@ impl DownloadedResource {
...
+                } else {
+                    tokio::fs::rename(&file, &dest).await
+                };
+                #[cfg(not(test))]
+                let rename_result = tokio::fs::rename(&file, &dest).await;
+
+                match rename_result {
+                    Ok(()) => {}
+                    Err(e) if e.raw_os_error() == Some(18) => {
+                        // 18 == EXDEV on Unix-like systems (cross-device link).
```
[the remark this answers is not in the document]
Comment (Mossaka) [reply crates/wassette/src/lib.rs:325]: I don't want an extra dep just for the constant

File: crates/wassette/src/lib.rs (hunk 2 above)
Comment (thomastaylor312) [reply crates/wassette/src/lib.rs]: Your logic was very clear to me fwiw
